services:
  - type: web
    name: imposer
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: IMPOSER_JWT_SECRET
        generateValue: true
